In [1]:
import numpy as np

In [10]:
a=np.arange(1,12)
b=np.arange(24,36).reshape(3,4)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [5]:
b

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [7]:
np.cumsum(b,axis=0)

array([[24, 25, 26, 27],
       [52, 54, 56, 58],
       [84, 87, 90, 93]])

In [8]:
np.cumsum(b,axis=1)

array([[ 24,  49,  75, 102],
       [ 28,  57,  87, 118],
       [ 32,  65,  99, 134]])

## cumprod()

In [11]:
np.cumprod(a)

array([       1,        2,        6,       24,      120,      720,
           5040,    40320,   362880,  3628800, 39916800])

In [12]:
np.cumprod(b,axis=1)

array([[     24,     600,   15600,  421200],
       [     28,     812,   24360,  755160],
       [     32,    1056,   35904, 1256640]])

In [13]:
np.cumprod(b,axis=0)

array([[   24,    25,    26,    27],
       [  672,   725,   780,   837],
       [21504, 23925, 26520, 29295]])