In [2]:
import numpy as np

In [6]:
a = np.random.randint(1,100,57)
b = np.arange(1,13).reshape(3,4)

In [9]:
a

array([91, 41, 54, 37, 37, 73, 64, 46, 56, 68, 31, 18, 13, 46, 55, 41,  2,
       39, 56, 17, 68, 73,  4, 34, 51, 74, 21, 58, 71, 15, 72, 96, 67, 52,
       65, 81, 70, 14, 15, 73, 61, 96, 90, 25, 20, 38, 74, 95, 74, 89,  1,
        9, 72, 63, 18, 11, 90], dtype=int32)

In [8]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([ 4,  8,  3,  6,  4,  7,  7, 10,  2,  6]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## co-relation co-efficient

In [11]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

np.corrcoef(a1,a2)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])