In [1]:
import numpy as np

In [2]:
a=np.arange(50).reshape(5,10)

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [10]:
item=[ i for i in range(12)]

In [11]:
item

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [12]:
np.isin(a,item)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [13]:
a[np.isin(a,item)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

flip()

In [15]:
b=np.arange(12)

In [17]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.flip(b)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [19]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
np.flip(a)

array([[49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])