In [1]:
import numpy as np

In [6]:
a = np.random.randint(1,90,15)
b = np.arange(1,13).reshape(3,4)

In [7]:
np.percentile(a,100)

np.float64(89.0)

In [8]:
np.percentile(a,0)

np.float64(6.0)

In [10]:
np.median(a)

np.float64(43.0)

In [13]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
np.percentile(b,100,axis=0)

array([ 9., 10., 11., 12.])

In [12]:
np.percentile(b,100,axis=1)

array([ 4.,  8., 12.])