In [1]:
import numpy as np

In [5]:
a=np.random.randint(-10,100,15)
a

array([  8,  24,   5,  28,  33,  73,  79,  99,  65,  87,   5,  91, -10,
         0,  67], dtype=int32)

In [6]:
np.sort(a)

array([-10,   0,   5,   5,   8,  24,  28,  33,  65,  67,  73,  79,  87,
        91,  99], dtype=int32)

In [14]:
#descending sorting
np.sort(a)[::-1]


array([ 99,  91,  87,  79,  73,  67,  65,  33,  28,  24,   8,   5,   5,
         0, -10], dtype=int32)

In [11]:
b=np.random.randint(-10,100,20).reshape(4,5)


np.sort(b)

array([[  1,  38,  44,  87,  90],
       [ 57,  63,  69,  84,  88],
       [-10,  44,  45,  55,  75],
       [ -1,  43,  57,  60,  98]], dtype=int32)

In [13]:
#column wise sorting
np.sort(b,axis=0)

array([[ -1,  44,  75, -10,  38],
       [ 45,  44,  84,   1,  43],
       [ 57,  57,  90,  60,  55],
       [ 87,  69,  98,  63,  88]], dtype=int32)