In [1]:
import numpy as np

In [15]:
a=np.random.randint(1,10,15)
b=np.random.randint(1,10,50)

In [16]:
a

array([7, 5, 4, 1, 9, 4, 4, 8, 4, 7, 4, 7, 2, 6, 6], dtype=int32)

In [17]:
np.unique(a)

array([1, 2, 4, 5, 6, 7, 8, 9], dtype=int32)

In [18]:
b

array([9, 2, 2, 3, 8, 1, 7, 4, 5, 4, 7, 5, 7, 4, 5, 2, 1, 8, 5, 2, 3, 5,
       5, 7, 9, 3, 5, 1, 1, 1, 6, 7, 4, 4, 4, 2, 4, 3, 5, 7, 3, 2, 4, 2,
       1, 7, 1, 7, 7, 4], dtype=int32)

In [19]:
np.unique(b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)