## where()

In [1]:
import numpy as np

In [20]:
b=np.arange(12).reshape(3,4)

In [10]:
a=np.random.randint(1,50,50)

In [11]:
np.where(a>25)

(array([ 0,  1, 10, 11, 13, 16, 17, 18, 21, 22, 23, 28, 29, 32, 34, 35, 36,
        39, 41, 43, 44, 45, 46, 47]),)

In [12]:
np.where(a%2==0,'even','odd')

array(['odd', 'odd', 'even', 'even', 'even', 'odd', 'even', 'odd', 'even',
       'even', 'odd', 'odd', 'odd', 'even', 'odd', 'even', 'odd', 'odd',
       'odd', 'odd', 'even', 'even', 'odd', 'even', 'odd', 'odd', 'even',
       'even', 'even', 'even', 'even', 'odd', 'odd', 'even', 'odd', 'odd',
       'odd', 'even', 'odd', 'odd', 'even', 'even', 'even', 'odd', 'even',
       'even', 'odd', 'even', 'odd', 'even'], dtype='<U4')

## argmax()

In [15]:
a

array([43, 33, 14, 12, 18,  9,  2,  3,  6, 22, 41, 29,  9, 44, 17, 24, 33,
       49, 37, 21, 18, 44, 39, 26, 25,  1,  4,  6, 42, 34, 12, 13, 37, 20,
       33, 33, 33, 12,  1, 35, 24, 44, 14, 35, 34, 26, 39, 36, 17,  4],
      dtype=int32)

In [13]:
np.argmax(a)

np.int64(17)

In [21]:
a[17]

np.int32(49)

In [22]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.argmin(b)

np.int64(0)

## argmin()

In [18]:
a

array([43, 33, 14, 12, 18,  9,  2,  3,  6, 22, 41, 29,  9, 44, 17, 24, 33,
       49, 37, 21, 18, 44, 39, 26, 25,  1,  4,  6, 42, 34, 12, 13, 37, 20,
       33, 33, 33, 12,  1, 35, 24, 44, 14, 35, 34, 26, 39, 36, 17,  4],
      dtype=int32)

In [16]:
np.argmin(a)

np.int64(25)

In [17]:
a[25]

np.int32(1)