In [1]:
import numpy as np

In [2]:
a1=np.arange(12)
a2=np.arange(12).reshape(3,4)
a3=np.arange(27).reshape(3,3,3)

In [5]:
for i  in a1:
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [4]:
for i  in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [6]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [8]:
for i in np.nditer(a3):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 