In [1]:
import numpy as np

In [3]:
a1=np.arange(10).reshape(2,5)
print(a1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Trigonometric function

In [5]:
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [6]:
np.cos(a1)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026]])

### custom formula in numpy array 

### sigmoid function
### s(x)=1/(1+e^-x)

In [7]:
def sigmoid(array):
    return 1/(1+np.exp(-(array)))

a1=np.arange(10)
print(sigmoid(a1))


[0.5        0.73105858 0.88079708 0.95257413 0.98201379 0.99330715
 0.99752738 0.99908895 0.99966465 0.99987661]


### loss function
### mean square error
### 

In [13]:
actual=np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)

print(actual)
print(predicted)

[20 19 39 17 10 29 21 31 33 20  9 35 12  8 37 23  1 25 40 14 23 19 41 14
 34]
[47 10 49  1 25  4  4 44 29 45 10 48 23 34 45 23  6 40 13 39 25 28 34 37
 13]


In [14]:
def ems(actual,predicted):
    return( np.mean(actual-predicted)**2)


ems(actual , predicted)

np.float64(16.6464)

### Binary loss entropy