In [1]:
import numpy as np

In [ ]:
# same shape
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [ ]:
# different shape
a=np.arange(6).reshape(2,3)
b=np.arange(6,9).reshape(1,3)

print(a)
print(b)

print()

print(a+b) 

[[0 1 2]
 [3 4 5]]
[[6 7 8]]

[[ 6  8 10]
 [ 9 11 13]]


### To The broadcasting describe how numpy array threat with different shape during arithmetic operation.  
### The smaller array broadcast across the larger array so that they have compatible shapes.  
### Broadcasting Rule
### i)  Make the two array have same number of dimension.
### ii) Make each dimension of two array the same shape.

Numpy array automatically broadcasting

In [3]:
a1=np.arange(12).reshape(4,3)
a2=np.arange(3)

print(a1)
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]


In [4]:
print(a1+a2)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [6]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(3)

print(a1+a2)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [7]:
a1=np.arange(4).reshape(1,4)
a2=np.arange(4).reshape(4,1)

print(a1+a2)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [8]:
a1=np.arange(4).reshape(2,2)
a2=np.arange(1)

print(a1+a2)

[[0 1]
 [2 3]]


In [9]:
a1=np.arange(12).reshape(4,3)
a2=np.arange(12).reshape(3,4)

print(a1+a2)

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [10]:
a1=np.arange(16).reshape(4,4)
a2=np.arange(4).reshape(2,2)

print(a1+a2)

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 