In [1]:
import numpy as np

In [2]:
arr1=np.arange(12).reshape(3,4)

In [3]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
arr2=np.arange(12).reshape(4,3)

In [6]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
np.dot(arr1,arr2)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

## Try another example

In [8]:
arr3=np.arange(6).reshape(3,2)

In [9]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
arr4=np.arange(6).reshape(2,3)

In [11]:
arr4

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
np.dot(arr3,arr4)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])