# Mathematical Function

In [ ]:
import numpy as np

In [7]:
a1=np.arange(1,13).reshape(4,3)

In [8]:
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.max(a1,axis=1)

array([ 3,  6,  9, 12])

In [9]:
a1.max()

np.int64(12)

In [14]:
np.min(a1,axis=1)

array([ 1,  4,  7, 10])

In [10]:
a1.min()

np.int64(1)

In [11]:
a1.prod()

np.int64(479001600)

In [12]:
a1.sum()

np.int64(78)