In [2]:
import numpy as np

In [7]:
arr2=np.arange(6,12).reshape(3,2)

In [8]:
arr2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [9]:
np.log(arr2)

array([[1.79175947, 1.94591015],
       [2.07944154, 2.19722458],
       [2.30258509, 2.39789527]])

In [10]:
np.exp(arr2)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [25]:
arr4=np.arange(8,16).reshape(2,4)


In [29]:
arr4/10

array([[0.8, 0.9, 1. , 1.1],
       [1.2, 1.3, 1.4, 1.5]])

In [30]:
np.round(arr4/10)

array([[1., 1., 1., 1.],
       [1., 1., 1., 2.]])

In [31]:
np.floor(arr4/10)

array([[0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.ceil(arr4/10)

array([[1., 1., 1., 2.],
       [2., 2., 2., 2.]])