In [1]:
import numpy as np

In [4]:
a1=np.arange(12,24).reshape(4,3)

In [5]:
a1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a1.mean()

np.float64(17.5)

In [7]:
a1.std()

np.float64(3.452052529534663)

In [10]:
np.median(a1)

np.float64(17.5)

In [11]:
np.median(a1, axis=1)

array([13., 16., 19., 22.])

In [12]:
np.var(a1)

np.float64(11.916666666666666)

In [14]:
np.var(a1)

np.float64(11.916666666666666)

In [15]:
np.var(a1, axis=1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])