In [1]:
import numpy as np

## Stacking

In [2]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

### Horizontal stack

In [15]:
a3=np.hstack((a1,a2))
print(a3)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


### Vertical stack

In [8]:
a4=np.vstack((a2,a1))
print(a4)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Splitting 

In [12]:
np.hsplit(a3,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [16]:
np.vsplit(a4,2)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]