In [1]:
import numpy as np

it gives in numpy array result

In [8]:
a =np.arange(12)
b =np.arange(12,24)

In [9]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
b

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [11]:
np.union1d(a,b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
np.intersect1d(a,b)

array([], dtype=int64)

In [14]:
np.setdiff1d(a,b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
np.setxor1d(a,b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
np.in1d(a,[2,3,4])

C:\Users\Waheed khan\AppData\Local\Temp\ipykernel_5500\3873768478.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,[2,3,4])


array([False, False,  True,  True,  True, False, False, False, False,
       False, False, False])

In [17]:
a[np.in1d(a,[2,3,4])]

C:\Users\Waheed khan\AppData\Local\Temp\ipykernel_5500\3590559755.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  a[np.in1d(a,[2,3,4])]


array([2, 3, 4])