In [1]:
import numpy as np

In [2]:
a1=np.arange(12)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

## Indexing

In [23]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a1[-1]

np.int64(11)

In [5]:
a1[0]

np.int64(0)

In [6]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# To access 6
a2[1,2]

np.int64(6)

In [11]:
## To access 9
a2[2,1]

np.int64(9)

In [12]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# to access 5
a3[1,0,1]

np.int64(5)

In [16]:
# to access 0
a3[0,0,0]

np.int64(0)

In [17]:
# to access 3
a3[0,1,1]

np.int64(3)

## Advance indexing

### Methods
### i)  Fancy indexing
### ii) Boolean indexing

#### i) Fancy indexing

In [3]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Provide a list of rows
a2[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [6]:
a2[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

#### ii) Boolean indexing

In [14]:
a4=np.random.randint(1,100,24).reshape(4,6)
a4

array([[87, 30, 23, 45, 12,  3],
       [64, 47, 79, 42, 13, 15],
       [39, 69, 66, 52, 88, 22],
       [13, 93, 32, 63, 86, 57]], dtype=int32)

find the item in array greater than 50

In [15]:
a4>50

array([[ True, False, False, False, False, False],
       [ True, False,  True, False, False, False],
       [False,  True,  True,  True,  True, False],
       [False,  True, False,  True,  True,  True]])

In [16]:
a4[a4>50]

array([87, 64, 79, 69, 66, 52, 88, 93, 63, 86, 57], dtype=int32)

In [18]:
# to find the even number
a4[a4%2==0]

array([30, 12, 64, 42, 66, 52, 88, 22, 32, 86], dtype=int32)

In [22]:
# To find even number which greater than 50

a4[(a4>50) & (a4%2==0)]

array([64, 66, 52, 88, 86], dtype=int32)