In [1]:
import numpy as np

In [30]:
a1=np.arange(12)
a2=np.arange(12).reshape(3,4)
a3=np.arange(27).reshape(3,3,3)

In [3]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
a1[2:10:2]

array([2, 4, 6, 8])

In [7]:
# access 3,5,9
a1[3:9:2]

array([3, 5, 7])

In [8]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
# access the 0,1,2,3
a2[0,:]

array([0, 1, 2, 3])

In [10]:
# access the 0,4,8
a2[:,0]

array([0, 4, 8])

In [12]:
# access 5,6 ,9,10
#last is not  included(3)
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [16]:
a2[1,2:4]

array([6, 7])

In [19]:
# access 0 3 8 11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [20]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# access 1 3 9 11 
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [23]:
# access 4 7
a2[1,::3]

array([4, 7])

In [26]:
# access 123 567
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [28]:
# access 567
a2[1,1:]

array([5, 6, 7])

## Working on 3D array

In [31]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [34]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
# access 345
a3[0,1,:]

array([3, 4, 5])

In [37]:
# 10 13  16
a3[1,:,1]

array([10, 13, 16])

In [38]:
# 22 23 25 26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [40]:
# 0 2 18 20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [41]:
# 4 5 13  14 22 23
a3[:,1::3,1:]

array([[[ 4,  5]],

       [[13, 14]],

       [[22, 23]]])