### Changing the data type

In [1]:
import numpy as np

In [2]:
tensor=np.array([[[1,3,4],[1,24,7]],[[21,42,53],[21,43,44]]])
print(tensor)

[[[ 1  3  4]
  [ 1 24  7]]

 [[21 42 53]
  [21 43 44]]]


In [4]:
tensor.dtype

dtype('int64')

In [6]:
tensor.astype(np.int16)

array([[[ 1,  3,  4],
        [ 1, 24,  7]],

       [[21, 42, 53],
        [21, 43, 44]]], dtype=int16)