### Creating a numpy array 

In [1]:
import numpy as np



### Creating a 1D array

In [5]:
arr=np.array([1,2,3,5])
print(arr)
type(arr)

[1 2 3 5]


numpy.ndarray

### Creating a 2D array

In [9]:
arr2=np.array([[1,3,4],[1,24,7]])
print(arr2)
type(arr2)

[[ 1  3  4]
 [ 1 24  7]]


numpy.ndarray

### Creating a 3D array

In [12]:
arr3=np.array([[[1,3,4],[1,24,7]],[[21,42,53],[21,43,44]]])
print(arr3)


[[[ 1  3  4]
  [ 1 24  7]]

 [[21 42 53]
  [21 43 44]]]


### Creating any data type array

In [14]:
arr=np.array([1,2.3,3.5,5])
print(arr)

[1.  2.3 3.5 5. ]


In [16]:
np.array([1,4,6,21,0,9],dtype='bool')

array([ True,  True,  True,  True, False,  True])

In [17]:
np.array([1,4,6,21,0,9],dtype='float')

array([ 1.,  4.,  6., 21.,  0.,  9.])

In [18]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.arange(0,20,2).reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [21]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.random.random((4,3))

array([[0.94548596, 0.64934268, 0.22160772],
       [0.76299657, 0.79285995, 0.80367877],
       [0.11846409, 0.65470129, 0.39087917],
       [0.95701918, 0.34056129, 0.29825042]])

In [30]:
np.linspace(20,100,10)

array([ 20.        ,  28.88888889,  37.77777778,  46.66666667,
        55.55555556,  64.44444444,  73.33333333,  82.22222222,
        91.11111111, 100.        ])

In [29]:
np.linspace(20,100,10).reshape(5,2)

array([[ 20.        ,  28.88888889],
       [ 37.77777778,  46.66666667],
       [ 55.55555556,  64.44444444],
       [ 73.33333333,  82.22222222],
       [ 91.11111111, 100.        ]])

In [28]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])