#### Numpy Attribute

In [2]:
import numpy as np

In [3]:
vector=np.array([1,2,3,5])
print(vector)

[1 2 3 5]


In [9]:
matrix=np.array([[1.3,3.4,4.5],[1.3,2.4,7.5]])
print(matrix)

[[1.3 3.4 4.5]
 [1.3 2.4 7.5]]


In [5]:
tensor=np.array([[[1,3,4],[1,24,7]],[[21,42,53],[21,43,44]]])
print(tensor)

[[[ 1  3  4]
  [ 1 24  7]]

 [[21 42 53]
  [21 43 44]]]


In [6]:
print(vector.ndim)
print(matrix.ndim)
print(tensor.ndim)

1
2
3


In [7]:
print(vector.shape)
print(matrix.shape)
print(tensor.shape)

(4,)
(2, 3)
(2, 2, 3)


In [8]:
print(vector.size)
print(matrix.size)
print(tensor.size)

4
6
12


In [10]:
print(vector.itemsize)
print(matrix.itemsize)
print(tensor.itemsize)

8
8
8


In [11]:
print(vector.dtype)
print(matrix.dtype)
print(tensor.dtype)

int64
float64
int64
