In [1]:
import numpy as np

In [4]:
b=np.array([1,2,3,4,np.nan,8])
b

array([ 1.,  2.,  3.,  4., nan,  8.])

In [5]:
np.isnan(b)

array([False, False, False, False,  True, False])

In [9]:
b[~np.isnan(b)]

array([1., 2., 3., 4., 8.])